apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-standalone
spec:
  serviceName: mongodb-svc
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
        selector: elastic-standalone
    spec:
      containers:
        - name: mongodb-standalone
          image: mongo:4.0.8
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  type: NodePort
  selector:
    app: elastic
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32017
